### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by s-crypt** [szimek/sharedrop#116]
There is not much documentation on this project, so I have a few questions.
* Is the data or metadata encrypted peer to peer?
   * If not E2EE, is the data encrypted at all?
* Does the data get sent to a server when a transfer is over a local network?

**Comment by szimek** [comment]
Hey!

I agree that it could be explained a bit better in both the app itself and this repo.

You can read about security in WebRTC e.g. https://webrtc-security.github.io/ or https://bloggeek.me/is-webrtc-safe/.

The only data that  does *not* go through P2P connection is the initial exchange of message required to establish P2P connection (so called signaling). All the other data, i.e. file metadata (e.g. its name) and the file data itself is sent through WebRTC P2P encrypted data channel.
