### ISSUE TITLE
Brave browser not discoverable

### ISSUE THREAD

**Issue by ChitranshuV** [szimek/sharedrop#118]
I'm running Brave on my Windows computer (Version 1.26.67, Chromium: 91.0.4472.114) as well as Android phone (Version 1.25.73, Chromium: 91.0.4472.106). But both my devices cannot discover each other in sharedrop. I opened the site in Google Chrome on both devices and they didn't have any trouble. I checked my public IP on both devices through Brave on some site and it shows same IP address.

I have seen that Brave isn't mentioned in supported browsers but since both Edge and Google Chrome seems to work fine, I was expecting Brave too. They all are Chromium.

Is this a bug? Can it be resolved?

**Comment by szimek** [comment]
Hey!

Just to clarify - the devices can see each other when you use Chrome on both, but don't when you use Brave on one of them?

Does it work when you use Brave and Chrome on the same WIndows device?
Does it work if you create a custom room and open it on both devices?

**Comment by ChitranshuV** [comment]
I tried to open both browsers on both the devices and they can discover each other just fine. I don't know why I couldn't reproduce this bug today. Initially not all users seem to discover but then I refreshed the pages and they could discover each other. 

You can close this issue.
