### ISSUE TITLE
"It was not possible to establish a direct connection with the other peer" error when trying to send a file

### ISSUE THREAD

**Issue by K4LCIFER** [szimek/sharedrop#121]
I'm trying to send a file over separate networks, but It will not work. It just throws the aforementioned error.

**Comment by Bananamon** [comment]
this has been happening to me for only one device (laptop1) which is on the same network. other devices can see this laptop but cannot share to it

Windows 10 21H1 OS build 19043.1237
Firefox 93.0 (64 bit)
installed extensions: ublock origin, Firefox tracking is set to Strict

I have a second laptop (laptop2) and a phone. both have Firefox and ublock origin and can receive files on sharedrop no problem. it is only sending to laptop1 that says the "direct connection with the other peer" error

**Comment by qnkhuat** [comment]
I get this error on my personal project too, couldn't figure out why. Hopefully there are some webrtc expert could come and help us with this

**Comment by qnkhuat** [comment]
resolved this by adding a TURN server :)

**Comment by szimek** [comment]
Most cases of this error could be solved by adding a TURN server. 

However, the main issue is the cost. Currently, running this app costs only a few $ per month. There are companies like e.g. Twilio or Xirsys that provide a paid TURN service, but as it's based on amount of GB transferred, it's really hard to predict the final cost.

Unfortunately, there's not much I can do about it, unless, one of such companies would like to sponsor this app and provide a free TURN service :)
