### ISSUE TITLE
Any way to send to multiple devices?

### ISSUE THREAD

**Issue by superflo22** [szimek/sharedrop#126]
Is there any way to select a few devices and send them the same files in one go?

**Comment by szimek** [comment]
Unfortunately, not. For use cases with many devices, something like https://instant.io/ (based on BitTorrent) could be more helpful.

If you have an idea how this could be implemented, even if only from UX perspective, I'm open to suggestions.

**Comment by superflo22** [comment]
Thank you for pointing me towards WebTorrent.
Will check that out and close this for now.
