### ISSUE TITLE
Docker image is preferred

### ISSUE THREAD

**Issue by henrywithu** [szimek/sharedrop#132]
Thanks for the great app. It'll be much appreciated if there's an official image on DockerHub, for easier deployment.

**Comment by diamondsw** [comment]
Agreed, as the current Dockerfile appears to be broken:

`me@docker sharedrop $ docker-compose build --no-cache
Building sharedrop
Sending build context to Docker daemon  1.233MB
Step 1/8 : FROM node:14-buster
 ---> 41706aa77d80
Step 2/8 : RUN mkdir -p /srv/app
 ---> Running in 0002e6a93cd0
Removing intermediate container 0002e6a93cd0
 ---> 5793a813ca87
Step 3/8 : WORKDIR /srv/app
 ---> Running in e39cb6ed9894
Removing intermediate container e39cb6ed9894
 ---> 2af7cda86e6c
Step 4/8 : COPY package.json yarn.lock ./
 ---> b6be1219b8fd
Step 5/8 : RUN yarn --frozen-lockfile --non-interactive
 ---> Running in c80397aad68a
yarn install v1.22.19
[1/5] Validating package.json...
error sharedrop@1.0.0: The engine "node" is incompatible with this module. Expected version "^12.21.0". Got "14.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn --frozen-lockfile --non-interactive' returned a non-zero code: 1
ERROR: Service 'sharedrop' failed to build : Build failed
`

**Comment by benjamin051000** [comment]
It's been a while, but `docker build .` worked for me on the latest clone of the master branch.
