### ISSUE TITLE
[tell me] how does this compare to snapdrop.io?

### ISSUE THREAD

**Issue by SiddharthSharma16923** [szimek/sharedrop#135]
are they twins?

**Comment by szimek** [comment]
> are they twins?

Almost ;) sharedrop.io was released in early 2014, a bit before snapdrop.io (late 2015?).

Besides smaller differences (UI, PWA, etc.) the main differences are:
- snapdrop.io uses web sockets as a fallback when direct p2p connection can't be established; this can be perceived as an advantage (and most likely is by most people), as it works in more cases than sharedrop.io, but also as a disadvantage, as transferred files are moved through a third-party server; I don't know if/how they are encrypted in such case
- sharedrop.io allows one to share files between networks via custom room names
