### ISSUE TITLE
Add note in About page that it does not work with a VPN activated

### ISSUE THREAD

**Issue by ldealmei** [szimek/sharedrop#150]
Thanks for sharedrop it works great!

I'm used to my VPN getting in the way of apps, so it's always the first thing I deactivate if something seems to not work as expected.

However it would improve user experience to specify in the About page (shown the first time we visit sharedrop) that it does not work with a VPN activated. 

I'll submit a PR for this.

**Comment by MaoHolden** [comment]
@ldealmei @szimek Hello, just wondering if you know the details of why It doesn't work on VPNs, I was digging into the issues but couldn't find more info. Would be great to expand the note with some sweet tech details n.n.
