### ISSUE TITLE
Query about firebase database!

### ISSUE THREAD

**Issue by priyanshu-kun** [szimek/sharedrop#153]
@szimek  In Firebase there are 3 types of databases and those are Firestore, real-time db, and storage could you please be more clear in the documentation about which type of db is required in order to set up sharedrop locally?

**Comment by szimek** [comment]
Hi! At the time I wrote this app, there was only one :)

It's the "Realtime Database".

**Comment by szimek** [comment]
I'm closing it, but feel free to reopen it if you have any other questions.
